import uuid
import enum
from typing import TYPE_CHECKING, List, Optional
from datetime import datetime
from sqlalchemy import String, Text, DateTime, Boolean, Numeric, UUID, ForeignKey, Enum as SQLEnum, Integer
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.base import TimestampMixin

if TYPE_CHECKING:
    from app.models.user import User
    from app.models.post import Post

class MenuStatusEnum(str, enum.Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"

class RecommendationStatusEnum(str, enum.Enum):
    ACTIVE = "ACTIVE"
    ACTED_UPON = "ACTED_UPON"
    EXPIRED = "EXPIRED"

class Menu(Base, TimestampMixin):
    """Menu Entity representing a versioned restaurant menu."""
    __tablename__ = "menus"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    version_number: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    status: Mapped[MenuStatusEnum] = mapped_column(SQLEnum(MenuStatusEnum, name="menu_status_enum"), default=MenuStatusEnum.DRAFT, nullable=False)
    source_url: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    items: Mapped[List["MenuItem"]] = relationship("MenuItem", back_populates="menu", cascade="all, delete-orphan")
    user: Mapped["User"] = relationship("User", foreign_keys=[user_id])

class MenuItem(Base, TimestampMixin):
    """Individual menu item attached to a specific menu version."""
    __tablename__ = "menu_items"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    menu_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("menus.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    price: Mapped[Optional[float]] = mapped_column(Numeric(10, 2), nullable=True)
    category: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    menu: Mapped["Menu"] = relationship("Menu", back_populates="items")
    recommendations: Mapped[List["PostRecommendation"]] = relationship("PostRecommendation", back_populates="menu_item", cascade="all, delete-orphan")
    posts: Mapped[List["Post"]] = relationship("Post", back_populates="menu_item")

class PostRecommendation(Base, TimestampMixin):
    """Actionable strategy generated by the Strategy Engine."""
    __tablename__ = "post_recommendations"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    menu_item_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("menu_items.id", ondelete="CASCADE"), nullable=False, index=True)
    reason_context: Mapped[str] = mapped_column(Text, nullable=False)
    suggested_angle: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    status: Mapped[RecommendationStatusEnum] = mapped_column(SQLEnum(RecommendationStatusEnum, name="recommendation_status_enum"), default=RecommendationStatusEnum.ACTIVE, nullable=False)

    menu_item: Mapped["MenuItem"] = relationship("MenuItem", back_populates="recommendations")
    posts: Mapped[List["Post"]] = relationship("Post", back_populates="recommendation")
