"""add menu intelligence models

Revision ID: d423591a297b
Revises: '2026_08_07_0004'
Create Date: 2026-08-09 22:02:28.686562

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd423591a297b'
down_revision: Union[str, None] = '2026_08_07_0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='menu_status_enum'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_user_id'), 'menus', ['user_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('menu_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_menu_id'), 'menu_items', ['menu_id'], unique=False)
    op.create_index(op.f('ix_menu_items_user_id'), 'menu_items', ['user_id'], unique=False)
    op.create_table('post_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('reason_context', sa.Text(), nullable=False),
    sa.Column('suggested_angle', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ACTED_UPON', 'EXPIRED', name='recommendation_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_recommendations_menu_item_id'), 'post_recommendations', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_post_recommendations_user_id'), 'post_recommendations', ['user_id'], unique=False)
    op.add_column('posts', sa.Column('menu_item_id', sa.UUID(), nullable=True))
    op.add_column('posts', sa.Column('recommendation_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_posts_menu_item_id'), 'posts', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_posts_recommendation_id'), 'posts', ['recommendation_id'], unique=False)
    op.create_foreign_key(None, 'posts', 'post_recommendations', ['recommendation_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'posts', 'menu_items', ['menu_item_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('tags_name_key'), 'tags', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tags_name_key'), 'tags', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_recommendation_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_menu_item_id'), table_name='posts')
    op.drop_column('posts', 'recommendation_id')
    op.drop_column('posts', 'menu_item_id')
    op.drop_index(op.f('ix_post_recommendations_user_id'), table_name='post_recommendations')
    op.drop_index(op.f('ix_post_recommendations_menu_item_id'), table_name='post_recommendations')
    op.drop_table('post_recommendations')
    op.drop_index(op.f('ix_menu_items_user_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_menu_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_menus_user_id'), table_name='menus')
    op.drop_table('menus')
    # ### end Alembic commands ###
